apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: msc-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /actuator/health
    port: 8080
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: msc-frondendconfig
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /api/healthcheck
    port: 3000
